version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:8.16.3
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false     # şifre korumasını kapatıyoruz

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch